-- MagnusBets Database Schema for Supabase
-- Run this SQL in the Supabase SQL Editor after creating your project

-- Create bets table
CREATE TABLE IF NOT EXISTS bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) DEFAULT NULL,
  event TEXT NOT NULL,
  wager DECIMAL(10, 2) NOT NULL,
  odds DECIMAL(10, 2) NOT NULL,
  outcome TEXT DEFAULT 'pending' CHECK (outcome IN ('pending', 'win', 'loss', 'push')),
  date TEXT NOT NULL,
  sport TEXT DEFAULT 'Basketball',
  league TEXT DEFAULT 'NBA',
  notes TEXT
);

-- Enable Row Level Security
ALTER TABLE bets ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (Phase 1: no auth required)
CREATE POLICY "Enable read access for all users" ON bets
  FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON bets
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON bets
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete access for all users" ON bets
  FOR DELETE USING (true);

-- For Phase 2 (with authentication), replace the above policies with:
/*
-- Drop public policies if they exist
DROP POLICY IF EXISTS "Enable read access for all users" ON bets;
DROP POLICY IF EXISTS "Enable insert access for all users" ON bets;
DROP POLICY IF EXISTS "Enable update access for all users" ON bets;
DROP POLICY IF EXISTS "Enable delete access for all users" ON bets;

-- Create user-specific policies
CREATE POLICY "Users can view their own bets" ON bets
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can insert their own bets" ON bets
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can update their own bets" ON bets
  FOR UPDATE USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can delete their own bets" ON bets
  FOR DELETE USING (auth.uid() = user_id OR user_id IS NULL);
*/

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS bets_user_id_idx ON bets(user_id);
CREATE INDEX IF NOT EXISTS bets_outcome_idx ON bets(outcome);
CREATE INDEX IF NOT EXISTS bets_date_idx ON bets(date);

-- Insert sample data (optional)
INSERT INTO bets (event, wager, odds, outcome, date, sport, league, notes) VALUES
  ('Lakers vs Warriors', 100.00, 2.10, 'win', '2024-02-10', 'Basketball', 'NBA', 'Model confidence high'),
  ('Celtics vs Nets', 50.00, 1.85, 'loss', '2024-02-09', 'Basketball', 'NBA', 'Close game'),
  ('Bucks vs Suns', 75.00, 1.95, 'win', '2024-02-08', 'Basketball', 'NBA', 'Star player out')
ON CONFLICT (id) DO NOTHING;

-- View to calculate user stats
CREATE OR REPLACE VIEW user_stats AS
SELECT 
  user_id,
  COUNT(*) as total_bets,
  SUM(CASE WHEN outcome = 'win' THEN 1 ELSE 0 END) as wins,
  SUM(CASE WHEN outcome = 'loss' THEN 1 ELSE 0 END) as losses,
  SUM(CASE WHEN outcome = 'push' THEN 1 ELSE 0 END) as pushes,
  SUM(CASE WHEN outcome = 'pending' THEN 1 ELSE 0 END) as pending,
  SUM(wager) as total_wagered,
  SUM(CASE 
    WHEN outcome = 'win' THEN wager * (odds - 1)
    WHEN outcome = 'loss' THEN -wager
    ELSE 0
  END) as total_profit,
  ROUND(
    CASE 
      WHEN SUM(wager) > 0 THEN 
        (SUM(CASE 
          WHEN outcome = 'win' THEN wager * (odds - 1)
          WHEN outcome = 'loss' THEN -wager
          ELSE 0
        END) / SUM(wager)) * 100
      ELSE 0
    END, 2
  ) as roi_percentage
FROM bets
GROUP BY user_id;

-- ====================================================================
-- Migration control function (one‑time setup)
-- Allows the assistant to run future schema changes without manual SQL.
-- Requires the Supabase service‑role key (already in your .env.local).
-- ====================================================================

CREATE OR REPLACE FUNCTION execute_sql(sql_text text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Optional: add safety checks here (e.g., forbid DROP, limit to certain patterns)
  -- For now we trust the service‑role key, which only you and the assistant possess.
  EXECUTE sql_text;
  RETURN json_build_object('success', true, 'message', 'SQL executed successfully');
EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION execute_sql IS 'Allows authorized clients (service‑role) to execute arbitrary SQL. Use with extreme caution.';